version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redisetlaunch
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
