version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redisetlaunch
    ports:
      - "5432:5432"
